config/routes.rb
Rails.application.routes.draw do
  root "spravka_lives#index"
  
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  get 'spravka_lives/close/:id' , to: 'spravka_lives#close', as: 'close'
  patch 'spravka_lives/change_flag/:id', to: 'spravka_lives#change_flag', as: 'change_flag'
  get 'archive', to: 'otdels#archive'
  patch 'otdels.:id', to: 'otdels#delete_position'
  get 'otdels/new_position/:id', to: 'otdels#new_position', as: 'new_position'
  post 'new_position/:otdel_id', to: 'otdels#create_position'
  resources :otdels
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  resources :spravka_lives
  
  
  
  
 end

app/models/otdel.rb
class Otdel < ApplicationRecord
  has_many :positions, through: :otdel_positions
  accepts_nested_attributes_for :positions
end

app/controllers/otdels_controller.rb
class OtdelsController < ApplicationController
  
  def index
    @otdels = Otdel.all
    @otdel_position = OtdelPosition.all
    @positions = Position.all
  end

  def new
    @otdel = Otdel.new
  end

  def new_position
    @otdel = Otdel.find(params[:id])
    @position = Position.new
    #@otdel_position = OtdelPosition.new
  end

  def create_position
    @position = Position.create(position_params)
    @position = Position.last
    @otdel_position = OtdelPosition.create(otdel_id: params[:otdel_id], position_id: @position.id)
    redirect_to otdels_path
  end

  def create
    @otdel = Otdel.new(otdel_params)
    if @otdel.save!
      redirect_to otdels_path
    end
  end

  def destroy
    @otdel = Otdel.find(params[:id])
    @otdel.destroy
    redirect_to otdels_path
  end

  def delete_position    
    @otdel_position = OtdelPosition.find(params[:id])
    @position = Position.find_by(id: @otdel_position.position_id)
    @position.destroy
    @otdel_position.destroy
    redirect_to otdels_path
  end

    private
    def otdel_params
      params.require(:otdel).permit(:name, positions_attributes: [:id, :name])
    end

    def position_params
      params.require(:position).permit(:id,:name)
    end
end

app/helpers/otdels_helper.rb
module OtdelsHelper
end

app/views/otdels/index.html.erb
<%= link_to 'new', new_otdel_path %>
<div>
<h1>Отделы</h1>
<% @otdels.each do |o| %>
<div class="testodin">
  <%= o.name %> 
  </div>
   
  <%= link_to "Добавить должность", new_position_path(o) %>
  <table>
    <% @otdel_position.where(otdel_id: o.id).each do |f| %>
    <tr>
      <td>
      <%= f.position.name %>
      </td>  
      <td>
      <%= link_to 'Удалить', otdels_path(f), method: :patch, data: { confirm: 'Вы уверены?' } %>
      </td>
      <% end %>
      </tr>

</table>
<% end %>
</div>

app/views/otdels/new.html.erb
<%= form_with(model: @otdel) do |f| %>
<%= f.text_field :name %>
<%= f.submit "Добавить отдел" %>
<% end %>

app/views/otdels/new_position.html.erb
<h2><%= @otdel.name %></h2>
<%= form_with(model: @position, url:"/new_position/#{params[:id]}/") do |f|  %>
 <%= f.text_field :name %>
 <%= f.submit "Добавить должность" %>
<% end %>