config/routes.rb
Rails.application.routes.draw do
  root "spravka_lives#index"
  
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  get 'spravka_lives/close/:id' , to: 'spravka_lives#close', as: 'close'
  patch 'spravka_lives/change_flag/:id', to: 'spravka_lives#change_flag', as: 'change_flag'
  get 'archive', to: 'otdels#archive'
  patch 'otdels.:id', to: 'otdels#delete_position'
  get 'otdels/new_position/:id', to: 'otdels#new_position', as: 'new_position'
  post 'new_position/:otdel_id', to: 'otdels#create_position'
  resources :otdels
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  resources :spravka_lives
  
  
  
  
 end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  include ActiveModel::SecurePassword
  validates :nick, uniqueness: true, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticated_user!
  before_action :reset_session
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.last_login = Time.now

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = 'Ваш аккаунт создан, можно приступить к работе'
      redirect_to root_path
    else
      render :new
  end
end


def user_params
  params.require(:user).permit(:nick, :password, :password_confirmation, :last_login)
end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<h1>Зарегистрироваться</h1>
<p>Создать новый аккаунт. Все поля обязательны для заполнения</p>

<% if @user.errors.any? %>
  <div class='alert alert-danger'>
    <p>Пожалуйста исправьте следующие ошибки</p>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <div class='form-group'>
    <%= f.label :Логин %>
    <%= f.text_field :nick, class: 'form-control' %>
  </div>
  
  <div class='form-group'>
    <%= f.label :Пароль %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= f.label :"Подтверждение пароля(еще раз пароль)" %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>
  <%= f.submit 'Зарегистрироваться', class: 'btn btn-primary' %>
<% end %>

<p class='mt-2'>
  Уже зарегистрированы <%= link_to 'Войти', login_path %>
</p>