config/routes.rb
Rails.application.routes.draw do
  root "spravka_lives#index"
  
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  get 'spravka_lives/close/:id' , to: 'spravka_lives#close', as: 'close'
  patch 'spravka_lives/change_flag/:id', to: 'spravka_lives#change_flag', as: 'change_flag'
  get 'archive', to: 'otdels#archive'
  patch 'otdels.:id', to: 'otdels#delete_position'
  get 'otdels/new_position/:id', to: 'otdels#new_position', as: 'new_position'
  post 'new_position/:otdel_id', to: 'otdels#create_position'
  resources :otdels
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  resources :spravka_lives
  
  
  
  
 end

app/controllers/spravka_lives_controller.rb
class SpravkaLivesController < ApplicationController
  #skip_before_action :authenticate_user!, :except => :destroy 
  before_action :set_spravka_life, only: [:show, :edit, :update, :destroy, :change_flag]
  
  def titleize(string)
    string.split(" ").map {|word| word.capitalize}.join(" ")
  end

  def gen(gena)
    if(gena == 'male')
      puts "он"
    else
      puts "она"
    end
  end

  # GET /spravka_lives
  # GET /spravka_lives.json
  
  def index
    @spravka_lives = SpravkaLife.where(flag: [0,1])
    #@spravka_lives_inprogress = SpravkaLife.where(flag: 1)
    @type_s = Stype.all
    
    
  end

  # GET /spravka_lives/1
  # GET /spravka_lives/1.json
  def show
    @print_form = true
    @spravka_lives = SpravkaLife.find(params[:id])
    name_for_datting = @spravka_life.name_s.split
    gender = Petrovich(firstname: name_for_datting[1]).gender
    @spravka_life.name_s = Petrovich(lastname: name_for_datting[0],firstname: name_for_datting[1], middlename: name_for_datting[2], gender: gender).genitive.to_s
        
    #render file: "/public/trudbook.xml", object: @spravka_lives

  end

  def close
    @print_form = true
    @spravka_lives = SpravkaLife.find(params[:id])
    name_for_datting = @spravka_lives.name_s.split
    @spravka_lives.name_s = Petrovich(lastname: name_for_datting[0],firstname: name_for_datting[1], middlename: name_for_datting[2]).dative.to_s
    gender = Petrovich(firstname: name_for_datting[1]).gender
    @gender = gen(gender)


        
  end

  def change_flag
    @spravka_lives = SpravkaLife.find(params[:id])
    @spravka_lives.update_attribute(:flag, "1")
    redirect_to root_path, notice: 'Данные справки обновлены' 

  end
  
  # GET /spravka_lives/new
  def new
    @spravka_life = SpravkaLife.new
    @type_s = Stype.all
    @comonform= Comonform.find_by(id: 1)
  end

  # GET /spravka_lives/1/edit
  def edit
    @type_s = Stype.all
    @flag = 1
    active_spravka = SpravkaLife.find(params[:id])
    
    @fields = FieldsForSpravka.find_by(stype_id: active_spravka.stype_id)
    @comonform= Comonform.find_by(id: 1)
    
    
    #@fields_work_book = []
    #@fields_work_place = {stavka:["Количество ставок",:text_field],prikaz_date:["Дата приказа", :date_field],prikaz_n:["Номер приказа", :text_field]}
    #@fields_vacation = {start_date:["начало отпуска",:date_field],finish_date:["Конец отпуска", :date_field],prikaz_date:["Дата приказа",:date_field], prikaz_n:["Номер приказа", :text_field]}
  end
  


  # POST /spravka_lives
  # POST /spravka_lives.json
  def create
    @comonform= Comonform.find_by(id: 1)
    @spravka_life = SpravkaLife.new(spravka_life_params)
    respond_to do |format|
      @spravka_life.flag = 0
      @spravka_life.position = @spravka_life.position.downcase
      @spravka_life.name_s = titleize(@spravka_life.name_s)  
      
      if @spravka_life.save
        
        format.html { redirect_to new_spravka_life_url, notice: 'Справка успешно создана' }
        format.json { render :show, status: :created, location: @spravka_life }
      else
        format.html { render :new }
        format.json { render json: @spravka_life.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spravka_lives/1
  # PATCH/PUT /spravka_lives/1.json
  def update
    respond_to do |format|
      if @spravka_life.update(spravka_life_params)
        format.html { redirect_to @spravka_life, notice: 'Данные справки обновлены' }
        format.json { render :show, status: :ok, location: @spravka_life }
      else
        format.html { render :edit }
        format.json { render json: @spravka_life.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spravka_lives/1
  # DELETE /spravka_lives/1.json
  def destroy
    @spravka_life.destroy
    respond_to do |format|
      format.html { redirect_to spravka_lives_url, notice: 'Справка удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spravka_life
      @spravka_life = SpravkaLife.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def spravka_life_params
      params.require(:spravka_life).permit(:id, :name_s, :stype_id, :department, :position, :place, :stavka, :prikaz_date, :prikaz_n, :flag, stype_attributes: [:id, :name_s])
    end
end

app/helpers/spravka_lives_helper.rb
module SpravkaLivesHelper
end

app/views/spravka_lives/_form.html.erb
<p id="notice"><%= notice %></p>
<%= form_with(model: spravka_life, local: true) do |form| %>
  <% if @flag %>
    <% @type_s.each do |ts| %>
      <% if spravka_life.stype_id == ts.id %>
        <% spravka_type = ts.id %>
        <center><h3><%= ts.name_s %></h3></center>
      <% end %>
    <% end %>
  <% end %>

  <% if spravka_life.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(spravka_life.errors.count, "error") %></h2>

      <ul>
      <% spravka_life.errors.full_messages.each do | message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="tentest">
  <% @comonform.fields.each do |k,v| %> <!-- Основная форма, которая вклюячает в себя поле с ФИО, отдел, должность, место предоставления -->
        <div class="field">
          <%= form.label v[0], class: "twelvetest" %>
          <%= form.public_send(v[1],:"#{k}", class: 'thirteentest') %>
          </div>
        <% end%>

  

  <% unless @flag %>
    <div class="field">
    <%= form.label "Тип справки", class: "twelvetest" %>
    <p>
    
    <%= form.select(:stype_id,{}, {}, {:class=> 'fourteentest'})  do   %>
    <%= options_from_collection_for_select(Stype.all, :id, :name_s) %>
    <% end %>
    </p>
    </div>
  <% end %> 
  

  <% if @flag %>
  <%= form.hidden_field :flag, value: 1 %>
    <% if spravka_type = 1 %>
    <% end%>  
        
        <% @fields.fields.each do |k,v| %>
        <div class="field">
          <%= form.label v[0] %>
          <%=  form.public_send(v[1], :"#{k} ", class: 'thirteentest') %>
          </div>
        <% end%>
        
  
  <div class="actions">
  <%= form.submit "Создать заявку", class: "eleventest" %>
  </div>
    


  
   
  <% else %>
  <div class="actions">
    <%= form.submit "Создать заявку", class: "eleventest"  %>
  </div>
  <% end %>

  
<% end %>
</div>

app/views/spravka_lives/close.html.erb
<div class="srpavka_close">
<center><h1 class="zerotest">
КОМИТЕТ ЗДРАВООХРАНЕНИЯ КУРСКОЙ ОБЛАСТИ <br>
ОБЛАСТНОЕ  БЮДЖЕТНОЕ   УЧРЕЖДЕНИЕ  ЗДРАВООХРАНЕНИЯ <br>
«ОБЛАСТНОЙ  ПЕРИНАТАЛЬНЫЙ  ЦЕНТР» <br>
________________________________________________________________________________
                  
</h1>
</center>
<p class="onetest">
Вячеслава Клыкова пр-т, д.100,Курск, 305005 <br>                                              
главный врач  (4712) 32-50-33        <br>                                 
бухгалтерия    (4712) 32-57-71 <br>
тел./факс         (4712) 32-50-33    <br>                                                     
E-mail:  sekretar@opckursk.ru

_______________№________            
				
</p>

<div class="twotest">
<center><h2>СПРАВКА</h2></center>
<p class="body">
Дана <%= @spravka_lives.name_s %> в том, что <%= @gender %>
                                   
действительно работает  в  областном бюджетном учреждении здравоохранения «Областной перинатальный центр» в должности   <%= @spravka_lives.department %>, <%= @spravka_lives.position %>  на 

<%= @spravka_lives.stavka %> ставку(и)   (приказ от <%= @spravka_lives.prikaz_date %>  № <%= @spravka_lives.prikaz_n %>).
<br>
<span>
         Справка выдана для предоставления  в <%= @spravka_lives.place %>.
</span>
</p>
</div>
<p class="threetest">
Заместитель главного 
врача по кадровым вопросам                                                      
</p>
<p class="fourtest">
Н.Ю. Афанасьева
</p>
<div class="down">
<p class="ass">
<>
<%= link_to 'Венуться', root_path %> | 
<%= link_to 'Распечатать', change_flag_path(@spravka_lives), method: :patch, :onclick => 'window.print();'%>
</p>

app/views/spravka_lives/edit.html.erb
<h1>Обработка заявки</h1>

<%= render 'form', spravka_life: @spravka_life %>



<%= link_to 'Show', @spravka_life %> |
<%= link_to 'Back', spravka_lives_path %>

app/views/spravka_lives/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Имя</th>
      <th>Тип справки</th>
      <th>Ссылка на заявление</th>
      <th>Ссылка на справку</th>
      <th>Дата создания</th>
     
    </tr>
  </thead>

  <tbody>
    <% @spravka_lives.each do |spravka_life| %>
      <tr>
        <td><%= spravka_life.name_s %></td>  
        <% @type_s.each do |type_s|%>
        <% if type_s.id == spravka_life.stype_id%>
        <td><%= type_s.name_s %></td>
        
        <% if type_s.spravka_exist %>
          <td><%= link_to 'Заявление', spravka_life %></td>
          <% if spravka_life.flag == 1 %>
            <td><%= link_to 'Справка', close_path(spravka_life) %></td>
          <% else %>
          <td></td>  
          <% end %>
        <% else %>
            <td><%= link_to 'Заявление', spravka_life %></td>
            <td></td>
        <% end %>
        
          

            <!-- through the ass  -->
            
          <!--end ass -->

        <% end %>
        <% end %>
        <td><%= spravka_life.created_at.strftime("%d.%m.%Y") %></td>
        <!--<td><%= link_to 'Edit', edit_spravka_life_path(spravka_life) %></td>
        <td><%= link_to 'Destroy', spravka_life, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/spravka_lives/new.html.erb
<h1>Новая заявка</h1>

<%= render 'form', spravka_life: @spravka_life %>

<%= link_to 'Отмена', spravka_lives_path %>

app/views/spravka_lives/show.html.erb
<% if @spravka_life.stype_id == 1 %>
<div class="fivetest">
<p class="hetter">
Главному врачу ОБУЗ ОПЦ <br>В.И. Крестининой
<br>
отдел <%= @spravka_life.department %>, <%= @spravka_life.position %>
<br>
<%= @spravka_life.name_s %>
<br>
<br>
<br>
<br>

</p>
</div>
<center><h2>Заявление</h2></center>
<p class="seventest">
Прошу разрешить выдать мне копию моей трудовой книжки для предоставления в <%= @spravka_life.place %>.
</p>
<br>
<br>
<br>
<br>
<div class="down">
<div class="date_down">
<%= Date.today.strftime("%d.%m.%Y") %>
</div>
<div class="date_down">Подпись</div>
</div>

<% end %>

<% if @spravka_life.stype_id == 2 %>
<p class="hetter">
Главному врачу ОБУЗ ОПЦ <br>В.И. Крестининой
<br>
отдел <%= @spravka_life.department %>, <%= @spravka_life.position %>
<br>
от
<%= @spravka_life.name_s %>
<br>
<br>
<br>
<br>

</p>
<center><h2>Заявление</h2></center>
<p class="seventest">
Прошу  выдать справку с места работы для предоставления в <%= @spravka_life.place %>.
</p>
<br>
<br>
<br>
<br>
<div class="down">
<div class="date_down">
<%= Date.today.strftime("%d.%m.%Y") %>
</div>
<div class="date_down">Подпись</div>
</div>
<% end %>

<% if @spravka_life.stype_id == 3 %>
<p class="hetter">
Главному врачу ОБУЗ ОПЦ <br>В.И. Крестининой
<br>
отдел <%= @spravka_life.department %>, <%= @spravka_life.position %>
<br>
от
<%= @spravka_life.name_s %>
<br>
<br>
<br>
<br>

</p>
<center><h2>Заявление</h2></center>
<p class="body">
Прошу  выдать справку об отпуске для предоставления в <%= @spravka_life.place %>.
</p>
<br>
<br>
<br>
<br>
<div class="down">
<div class="date_down">
<%= Date.today.strftime("%d.%m.%Y") %>
</div>
<div class="date_down">Подпись</div>
</div>
<% end %>

<p class="ass">
<%= link_to 'Обработать', edit_spravka_life_path(@spravka_life) %> |
<%= link_to 'Венуться', root_path %> | 
<%= link_to 'Распечатать',root_path, :onclick => 'window.print();'%>
</p>