config/routes.rb
Rails.application.routes.draw do
  root "spravka_lives#index"
  
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  
  get 'spravka_lives/close/:id' , to: 'spravka_lives#close', as: 'close'
  patch 'spravka_lives/change_flag/:id', to: 'spravka_lives#change_flag', as: 'change_flag'
  get 'archive', to: 'otdels#archive'
  patch 'otdels.:id', to: 'otdels#delete_position'
  get 'otdels/new_position/:id', to: 'otdels#new_position', as: 'new_position'
  post 'new_position/:otdel_id', to: 'otdels#create_position'
  resources :otdels
  resources :sessions, only: [:create]
  resources :users, only: [:new, :create]
  resources :spravka_lives
  
  
  
  
 end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Справка |Приложение для взаимодействия с отдеом кадров ОПЦ|</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

  </head>

  <body>
  
  <% unless @print_form || session[:user_id].blank? %>
    <div class="seventeentest">
  <ul class="menu-main">
  <li class="">
    <%= link_to 'Главная', root_path %>
      
    </li>
    <li class="">
    <%= link_to 'Редактирование справочника', otdels_path %>
      
    </li>
    <li class="">
      <%= link_to 'Архив заявок', archive_path  %>
    </li>
    <li class="">
    <%= link_to 'Создать заявку для отдела кадров', new_spravka_life_path %>
      
    </li>
  </ul>
</div>
<% end %>
    <%= yield %>
  </body>
</html>